# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 26bc245ff90f931dce15e307dc8f80f71ce9e5ff22b1d0f892385b8ccc21aab2958b1382c563f8e5fa43b34c92a76efff6f2ec6cd8b557919662cd15caa5b404

test:
  secret_key_base: 57c29f95d8ae139393c33b4ab1922ff3e646d6dd642171938d80cfc22ef345abc92db14d522ea767fac9e579ea83ba9a1e99ec57e74045bc99cf8280a584c2dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
